SELECT ANIMAL_ID, NAME
FROM (
    SELECT
        a.ANIMAL_ID,
        a.NAME,
        (b.DATETIME - a.DATETIME) AS STAY_DAYS
    FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b
      ON a.ANIMAL_ID = b.ANIMAL_ID
    ORDER BY (b.DATETIME - a.DATETIME) DESC
)
WHERE ROWNUM <= 2;